-- MySQL Script generated by MySQL Workbench
-- dim. 31 janv. 2021 00:23:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sophrodyn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sophrodyn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sophrodyn` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sophrodyn` ;

-- -----------------------------------------------------
-- Table `sophrodyn`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sophrodyn`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `firstname` VARCHAR(64) NOT NULL,
  `lastname` VARCHAR(128) NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `picture` VARCHAR(512) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sophrodyn`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sophrodyn`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sophrodyn`.`link_user_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sophrodyn`.`link_user_admin` (
  `id_user` INT NOT NULL,
  `id_admin` INT NOT NULL,
  `role` VARCHAR(16) NULL DEFAULT NULL,
  INDEX `fk_link_user_admin_1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_link_user_admin_2_idx` (`id_admin` ASC) VISIBLE,
  CONSTRAINT `fk_link_user_admin_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `sophrodyn`.`users` (`id`),
  CONSTRAINT `fk_link_user_admin_2`
    FOREIGN KEY (`id_admin`)
    REFERENCES `sophrodyn`.`admin` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sophrodyn`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sophrodyn`.`profiles` (
  `id` INT NOT NULL,
  `firstname` VARCHAR(64) NOT NULL,
  `lastname` VARCHAR(128) NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `height` DECIMAL(5,0) NOT NULL,
  `weight` DECIMAL(5,0) NOT NULL,
  `picture` VARCHAR(512) NULL DEFAULT NULL,
  `id_userprofil` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profiles_1_idx` (`id_userprofil` ASC) VISIBLE,
  CONSTRAINT `fk_profiles_1`
    FOREIGN KEY (`id_userprofil`)
    REFERENCES `sophrodyn`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
